create database pi
go
use pi

--Feita
CREATE TABLE CURSO(
COD_CURSO INT IDENTITY PRIMARY KEY,
NOME_CURSO VARCHAR (20) NOT NULL)

--Feita
CREATE TABLE DISCIPLINA(
COD_DISCIPLINA INT IDENTITY PRIMARY KEY,
NOME_DISCIPLINA VARCHAR (30))

--Feita
CREATE TABLE CURRICULO(
COD_CURRICULO INT IDENTITY PRIMARY KEY,
SEMESTRE_GRADE INT NOT NULL,
COD_DISCIPLINA INT NOT NULL REFERENCES DISCIPLINA, 
COD_CURSO INT NOT NULL REFERENCES CURSO)
 
--Feita
CREATE TABLE PROFESSOR(
MATRICULA_PROFESSOR INT IDENTITY PRIMARY KEY,
NOME_PROFESSOR VARCHAR (100) NOT NULL)

--Feita
CREATE TABLE TURMA(
COD_TURMA INT IDENTITY PRIMARY KEY, 
COD_CURRICULO INT NOT NULL REFERENCES CURRICULO,
MATRICULA_PROFESSOR INT NOT NULL REFERENCES PROFESSOR,
SEMESTRE INT NOT NULL,
ANO INT NOT NULL)

--Feita
CREATE TABLE SECRETARIA(
MATRICULA_SECRETARIA INT IDENTITY PRIMARY KEY,
NOME_SECRETARIA VARCHAR (100) NOT NULL,
EMAIL_SECRETARIA VARCHAR (100) NOT NULL)

--Feita
CREATE TABLE SALA(
COD_SALA INT IDENTITY PRIMARY KEY,
TIPO VARCHAR (15) NOT NULL,
NOME_SALA VARCHAR (30),
DESCRICAO VARCHAR (100),
CAPACIDADE INT NOT NULL)

--Feita
CREATE TABLE AGENDA(
COD_AGENDA INT IDENTITY PRIMARY KEY,
DATA_AGENDADA DATE NOT NULL,
HORA TIME NOT NULL)

--Feita
CREATE TABLE AGENDA_SALA(
COD_AGENDA_SALA INT IDENTITY PRIMARY KEY,
STATUS VARCHAR (10) NOT NULL DEFAULT 'disponivel',
COD_SALA INT NOT NULL REFERENCES SALA,
COD_AGENDA INT NOT NULL REFERENCES AGENDA)

--Feita
CREATE TABLE RESERVA(
COD_RESERVA INT IDENTITY PRIMARY KEY,
COD_AGENDA_SALA INT NOT NULL REFERENCES AGENDA_SALA ON DELETE CASCADE,
COD_TURMA INT REFERENCES TURMA,
MATRICULA_SECRETARIA INT NOT NULL REFERENCES SECRETARIA,
MANUTENCAO BIT NOT NULL)
-----------------------------------------------------------------------
INSERT INTO CURSO (NOME_CURSO) VALUES ('Engenharia');
INSERT INTO CURSO (NOME_CURSO) VALUES ('Matemática');
INSERT INTO CURSO (NOME_CURSO) VALUES ('Computação');

INSERT INTO DISCIPLINA (NOME_DISCIPLINA) VALUES ('Cálculo');
INSERT INTO DISCIPLINA (NOME_DISCIPLINA) VALUES ('Física');
INSERT INTO DISCIPLINA (NOME_DISCIPLINA) VALUES ('Programação');

INSERT INTO PROFESSOR (NOME_PROFESSOR) VALUES ('Dr. José Silva');
INSERT INTO PROFESSOR (NOME_PROFESSOR) VALUES ('Dra. Maria Souza');
INSERT INTO PROFESSOR (NOME_PROFESSOR) VALUES ('Dr. Paulo Ribeiro');

INSERT INTO CURRICULO (SEMESTRE_GRADE, COD_DISCIPLINA, COD_CURSO) VALUES (1, 1, 1);
INSERT INTO CURRICULO (SEMESTRE_GRADE, COD_DISCIPLINA, COD_CURSO) VALUES (2, 2, 1);
INSERT INTO CURRICULO (SEMESTRE_GRADE, COD_DISCIPLINA, COD_CURSO) VALUES (1, 3, 2);

INSERT INTO SECRETARIA (NOME_SECRETARIA, EMAIL_SECRETARIA) VALUES ('Ana Mendes', 'ana.mendes@example.com');
INSERT INTO SECRETARIA (NOME_SECRETARIA, EMAIL_SECRETARIA) VALUES ('Carlos Ferreira', 'carlos.ferreira@example.com');
INSERT INTO SECRETARIA (NOME_SECRETARIA, EMAIL_SECRETARIA) VALUES ('Luciana Barbosa', 'luciana.barbosa@example.com');
INSERT INTO SECRETARIA (NOME_SECRETARIA, EMAIL_SECRETARIA) VALUES ('João Silva', 'joao.silva@example.com');
INSERT INTO SECRETARIA (NOME_SECRETARIA, EMAIL_SECRETARIA) VALUES ('Patrícia Costa', 'patricia.costa@example.com');

INSERT INTO SALA (TIPO, NOME_SALA, DESCRICAO, CAPACIDADE) VALUES 
('Aula', 'Sala 101', 'Sala de aula para cursos teóricos.', 30);
INSERT INTO SALA (TIPO, NOME_SALA, DESCRICAO, CAPACIDADE) VALUES 
('Laboratório', 'Lab 202', 'Laboratório com computadores para aulas práticas.', 25);
INSERT INTO SALA (TIPO, NOME_SALA, DESCRICAO, CAPACIDADE) VALUES 
('Auditório', 'Auditório Principal', 'Auditório para eventos e palestras.', 100);
INSERT INTO SALA (TIPO, NOME_SALA, DESCRICAO, CAPACIDADE) VALUES 
('Aula', 'Sala de Aula', 'Sala para reuniões administrativas.', 10);
INSERT INTO SALA (TIPO, NOME_SALA, DESCRICAO, CAPACIDADE) VALUES 
('Aula', 'Sala de Aula', 'Sala de aula', 15);

INSERT INTO TURMA (COD_CURRICULO, MATRICULA_PROFESSOR, SEMESTRE, ANO) VALUES (1, 1, 1, 2023);
INSERT INTO TURMA (COD_CURRICULO, MATRICULA_PROFESSOR, SEMESTRE, ANO) VALUES (2, 2, 2, 2023);
INSERT INTO TURMA (COD_CURRICULO, MATRICULA_PROFESSOR, SEMESTRE, ANO) VALUES (3, 3, 1, 2023);

INSERT INTO AGENDA (DATA_AGENDADA, HORA) VALUES ('2023-10-05', '08:00:00');
INSERT INTO AGENDA (DATA_AGENDADA, HORA) VALUES ('2023-10-06', '10:00:00');
INSERT INTO AGENDA (DATA_AGENDADA, HORA) VALUES ('2023-10-07', '14:00:00');

INSERT INTO AGENDA_SALA (STATUS, COD_SALA, COD_AGENDA) VALUES ('Reservado', 1, 1);
INSERT INTO AGENDA_SALA (STATUS, COD_SALA, COD_AGENDA) VALUES ('Disponível', 2, 2);
INSERT INTO AGENDA_SALA (STATUS, COD_SALA, COD_AGENDA) VALUES ('Reservado', 3, 3);

INSERT INTO RESERVA (COD_AGENDA_SALA, COD_TURMA, MATRICULA_SECRETARIA, MANUTENCAO) VALUES (1, 1, 1, 0);
INSERT INTO RESERVA (COD_AGENDA_SALA, COD_TURMA, MATRICULA_SECRETARIA, MANUTENCAO) VALUES (2, 2, 2, 1);
INSERT INTO RESERVA (COD_AGENDA_SALA, COD_TURMA, MATRICULA_SECRETARIA, MANUTENCAO) VALUES (3, 3, 1, 0);
